// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/admin/index.vue')['default']
    AuthorityManager: typeof import('./src/components/admin/views/authorityManager/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Layout: typeof import('./src/components/admin/layout/index.vue')['default']
    Login: typeof import('./src/components/layout/Login/index.vue')['default']
    MHead: typeof import('./src/components/layout/MHead/index.vue')['default']
    MInput: typeof import('./src/components/MInput/index.vue')['default']
    MovieManager: typeof import('./src/components/admin/views/movieManager/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserManager: typeof import('./src/components/admin/views/userManager/index.vue')['default']
  }
}
